server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;

  # assets com hash no nome podem cachear pesado; vídeos idem
  location ~* \.(js|css|mp4|webm|png|jpg|jpeg|svg|woff2)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
